version: '3.7'

services:
  children-page:
    container_name: children-page
    image: wnuk1988/childrenpage:v2
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
    depends_on:
      - db
    networks:
      - backend

  db:
    container_name: db
    ports:
      - "5432:5432"
    image: postgres
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ChildrenPage
    networks:
      - backend

networks:
  backend:
    driver: bridge